[package]
name = "mort"
version = "0.1.0"
edition = "2024"

[dependencies]
types = { path = "./types" }

[build-dependencies]
types = { path = "./types" }

[dev-dependencies]
criterion = { version = "0.7", features = ["html_reports"] }

[[bench]]
name = "perft"
harness = false
